In [4]:
import pandas as pd 
df1 = pd.read_csv("webrag_benchmark_results_1.csv")
df2 = pd.read_csv("webrag_benchmark_results_2.csv")
df3 = pd.read_csv("webrag_benchmark_results_3.csv")
df4 = pd.read_csv("webrag_benchmark_results_4.csv")
df5 = pd.read_csv("webrag_benchmark_results_5.csv")
df6 = pd.read_csv("webrag_benchmark_results_6.csv")
df7 = pd.read_csv("webrag_benchmark_results_7.csv")
df8 = pd.read_csv("webrag_benchmark_results_8.csv")
df9 = pd.read_csv("webrag_benchmark_results_9.csv")
df10 = pd.read_csv("webrag_benchmark_results_10.csv")

In [ ]:
df_all = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10], ignore_index=True)
df_all.to_csv("webrag_benchmark_results_all.csv", index=False)

,Timestamp,Original_Query,Optimized_Query,Target_URL,Fanout_Time_sec,Search_Time_sec,Parse_Time_sec,Total_Time_sec,Markdown_Length,Status
0,2026-05-20 14:42:39,When was Dhaka University established?,University of Dhaka,https://en.wikipedia.org/wiki/University_of_Dhaka,0.159,0.196,0.636,0.991,89476,Success
1,2026-05-20 14:42:46,Who is the current President of Bangladesh?,List of presidents of Bangladesh,https://en.wikipedia.org/wiki/List_of_presiden...,0.089,0.466,0.501,1.056,83377,Success
2,2026-05-20 14:42:51,What is the national flower of Bangladesh?,National flower of Bangladesh,https://en.wikipedia.org/wiki/Nymphaea_pubescens,0.081,0.160,0.365,0.606,28295,Success
3,2026-05-20 14:42:57,Tell me about the Padma Bridge.,Padma Bridge,https://en.wikipedia.org/wiki/Padma_Bridge,0.071,0.173,0.576,0.820,104086,Success
4,2026-05-20 14:43:03,Where is the Sundarbans located?,Sundarbans,https://en.wikipedia.org/wiki/Sundarbans,0.081,0.164,1.075,1.320,230117,Success

Empty DataFrame
Columns: [Timestamp, Original_Query, Optimized_Query, Target_URL, Fanout_Time_sec, Search_Time_sec, Parse_Time_sec, Total_Time_sec, Markdown_Length, Status]
Index: []